# Generated by Django 4.2.4 on 2023-10-17 11:55

import api.v1.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Owner', 'Owner'), ('Admin', 'Admin'), ('HR', 'HR'), ('Employee', 'Employee'), ('None', 'None')], default=api.v1.accounts.models.RoleChoices['NOT_SPECIFIED'], max_length=30),
        ),
    ]
