# Generated by Django 4.2.4 on 2023-10-19 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quota', models.PositiveIntegerField(default=10)),
                ('is_expired', models.BooleanField(default=False)),
                ('year', models.PositiveIntegerField()),
                ('expiry_days', models.IntegerField(default=365)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CasualLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quota', models.PositiveIntegerField(default=5)),
                ('is_expired', models.BooleanField(default=False)),
                ('year', models.PositiveIntegerField()),
                ('expiry_days', models.IntegerField(default=365)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_duration', models.CharField(choices=[('Half-Day Leave', 'HALF'), ('Full-Day Leave', 'FULL')], max_length=50)),
                ('leaves_required', models.IntegerField()),
                ('is_expired', models.BooleanField(default=False)),
                ('is_team_lead_approval', models.BooleanField(default=False)),
                ('is_hr_approval', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'PENDING'), ('Approved', 'APPROVED'), ('Rejected', 'REJECTED')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('annual_leave', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests_annual_leave', to='leave.annualleave')),
                ('casual_leave', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests_casual_leave', to='leave.casualleave')),
            ],
        ),
        migrations.CreateModel(
            name='SickLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quota', models.PositiveIntegerField(default=5)),
                ('is_expired', models.BooleanField(default=False)),
                ('year', models.PositiveIntegerField()),
                ('expiry_days', models.IntegerField(default=365)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TeamLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_lead_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('team_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_team_lead', to='leave.teamlead')),
                ('team_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_team_title', to='leave.teamtitle')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRequestTL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tl_comments', models.TextField()),
                ('is_team_lead_approval', models.BooleanField(default=False)),
                ('leave_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_request_tl_leave_request', to='leave.leaverequest')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRequestHR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hr_comments', models.TextField()),
                ('is_hr_approval', models.BooleanField(default=False)),
                ('leave_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_request_hr_leave_request', to='leave.leaverequest')),
            ],
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='sick_leave',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests_sick_leave', to='leave.sickleave'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sick_leave_balance', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('annual_leave_balance', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('casual_leave_balance', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('accumulative_balance', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('annual_leave', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='leave_balances_annual_leave', to='leave.annualleave')),
                ('casual_leave', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='leave_balances_casual_leave', to='leave.casualleave')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances_employee', to=settings.AUTH_USER_MODEL)),
                ('sick_leave', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='leave_balances_sick_leave', to='leave.sickleave')),
            ],
        ),
    ]
