# Generated by Django 4.2.4 on 2023-10-10 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='team_lead',
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='team_lead',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'Team-Lead'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams_as_lead', to=settings.AUTH_USER_MODEL),
        ),
    ]
