# Generated by Django 4.2.4 on 2023-10-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
