# Generated by Django 4.2.4 on 2023-10-22 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_leaverequest_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='leaves_required',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
