# Generated by Django 4.2.4 on 2023-10-04 09:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='employee_wants_food',
            new_name='is_lunch',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='date',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='time',
        ),
        migrations.RemoveField(
            model_name='review',
            name='meal',
        ),
        migrations.AddField(
            model_name='meal',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='meal',
            name='is_dinner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meal',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meals_review', to='meal.review'),
        ),
    ]
