# Generated by Django 4.2.4 on 2023-10-04 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meal', '0002_rename_employee_wants_food_meal_is_lunch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='attendees',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='review',
        ),
        migrations.RemoveField(
            model_name='review',
            name='attendee',
        ),
        migrations.CreateModel(
            name='MealReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_meals', to='meal.meal')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_reviews', to='meal.review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
