# Generated by Django 4.2.4 on 2023-10-05 08:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meal', '0003_remove_meal_attendees_remove_meal_review_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mealreview',
            unique_together={('user', 'meal')},
        ),
    ]
