# Generated by Django 4.2.4 on 2023-10-30 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_publicholiday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('AMBIGUOUS', 'Ambiguous'), ('ON_LEAVE', 'On Leave'), ('WORK_FROM_HOME', 'Work from Home')], default='Present', max_length=20),
        ),
    ]
